version: '3.8'

services:
  postgres-db:
    image: postgres:15-alpine
    container_name: nest-postgres
    restart: always
    environment:
      # Docker sẽ lấy giá trị từ file .env dán vào đây
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - '${DB_PORT}:5432' # Map cổng từ .env vào cổng 5432 của container
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - nest-network

  redis-cache:
    image: redis:7-alpine
    container_name: nest-redis
    restart: always
    ports:
      - '${REDIS_PORT}:6379'
    # Nếu muốn đặt pass cho redis:
    # command: redis-server --requirepass ${REDIS_PASSWORD}
    networks:
      - nest-network

volumes:
  postgres_data:

networks:
  nest-network:
    driver: bridge